service: serverless-workshop-codecon
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - local-dev
    start:
      port: 3001
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SERVERLESS_WORKSHOP_TABLE: serverless-workshop-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/serverless-workshop-${sls:stage}

functions:
  create:
    handler: src/controllers/Create.handler
    events:
      - httpApi:
          path: /create
          method: post
  redirect:
    handler: src/controllers/Redirect.handler
    events:
      - httpApi:
          path: /{linkId}
          method: get

resources:
  Resources:
    ServerlessWorkshopTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: linkId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: linkId
            KeyType: HASH
        TableName: serverless-workshop-${sls:stage}
